//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GroceryChef.Api.Migrations
{
    /// <inheritdoc />
    public partial class Create : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "grocerychef");

            migrationBuilder.CreateTable(
                name: "cart",
                schema: "grocerychef",
                columns: table => new
                {
                    id = table.Column<string>(type: "text", nullable: false),
                    name = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_cart", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "ingredients",
                schema: "grocerychef",
                columns: table => new
                {
                    id = table.Column<string>(type: "text", nullable: false),
                    name = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    shelf_life = table.Column<DateOnly>(type: "date", nullable: false),
                    is_allergy = table.Column<bool>(type: "boolean", nullable: false),
                    create_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_ingredients", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "recipes",
                schema: "grocerychef",
                columns: table => new
                {
                    id = table.Column<string>(type: "text", nullable: false),
                    name = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    description = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    content = table.Column<string>(type: "character varying(3000)", maxLength: 3000, nullable: false),
                    is_archived = table.Column<bool>(type: "boolean", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_recipes", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "cart_ingredient",
                schema: "grocerychef",
                columns: table => new
                {
                    cart_id = table.Column<string>(type: "text", nullable: false),
                    ingredients_id = table.Column<string>(type: "text", nullable: false),
                    ingrdient_id = table.Column<string>(type: "text", nullable: false),
                    quantity = table.Column<int>(type: "integer", nullable: false),
                    is_bought = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_cart_ingredient", x => new { x.cart_id, x.ingredients_id });
                    table.ForeignKey(
                        name: "fk_cart_ingredient_cart_cart_id",
                        column: x => x.cart_id,
                        principalSchema: "grocerychef",
                        principalTable: "cart",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_cart_ingredient_ingredients_ingredients_id",
                        column: x => x.ingredients_id,
                        principalSchema: "grocerychef",
                        principalTable: "ingredients",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "recipe_ingredients",
                schema: "grocerychef",
                columns: table => new
                {
                    recipe_id = table.Column<string>(type: "text", nullable: false),
                    ingredients_id = table.Column<string>(type: "text", nullable: false),
                    ingredient = table.Column<string>(type: "text", nullable: false),
                    create_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_recipe_ingredients", x => new { x.ingredients_id, x.recipe_id });
                    table.ForeignKey(
                        name: "fk_recipe_ingredients_ingredients_ingredients_id",
                        column: x => x.ingredients_id,
                        principalSchema: "grocerychef",
                        principalTable: "ingredients",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_recipe_ingredients_recipes_recipe_id",
                        column: x => x.recipe_id,
                        principalSchema: "grocerychef",
                        principalTable: "recipes",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_cart_ingredient_ingredients_id",
                schema: "grocerychef",
                table: "cart_ingredient",
                column: "ingredients_id");

            migrationBuilder.CreateIndex(
                name: "ix_recipe_ingredients_recipe_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "recipe_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "cart_ingredient",
                schema: "grocerychef");

            migrationBuilder.DropTable(
                name: "recipe_ingredients",
                schema: "grocerychef");

            migrationBuilder.DropTable(
                name: "cart",
                schema: "grocerychef");

            migrationBuilder.DropTable(
                name: "ingredients",
                schema: "grocerychef");

            migrationBuilder.DropTable(
                name: "recipes",
                schema: "grocerychef");
        }
    }
}
