//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GroceryChef.Api.Migrations
{
    /// <inheritdoc />
    public partial class Alters : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_recipe_ingredients_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropColumn(
                name: "ingredients_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.RenameColumn(
                name: "ingredient",
                schema: "grocerychef",
                table: "recipe_ingredients",
                newName: "ingredient_id");

            migrationBuilder.AddColumn<decimal>(
                name: "amount",
                schema: "grocerychef",
                table: "recipe_ingredients",
                type: "numeric",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<int>(
                name: "unit",
                schema: "grocerychef",
                table: "recipe_ingredients",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients",
                columns: new[] { "ingredient_id", "recipe_id" });

            migrationBuilder.AddForeignKey(
                name: "fk_recipe_ingredients_ingredients_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "ingredient_id",
                principalSchema: "grocerychef",
                principalTable: "ingredients",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_recipe_ingredients_ingredients_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropColumn(
                name: "amount",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropColumn(
                name: "unit",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.RenameColumn(
                name: "ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                newName: "ingredient");

            migrationBuilder.AddColumn<string>(
                name: "ingredients_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients",
                columns: new[] { "ingredients_id", "recipe_id" });

            migrationBuilder.AddForeignKey(
                name: "fk_recipe_ingredients_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "ingredients_id",
                principalSchema: "grocerychef",
                principalTable: "ingredients",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
