//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GroceryChef.Api.Migrations
{
    /// <inheritdoc />
    public partial class Alter_Ingredient : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "shelf_life",
                schema: "grocerychef",
                table: "ingredients");

            migrationBuilder.AddColumn<int>(
                name: "shelf_life_of_date",
                schema: "grocerychef",
                table: "ingredients",
                type: "integer",
                nullable: false,
                defaultValue: 0);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "shelf_life_of_date",
                schema: "grocerychef",
                table: "ingredients");

            migrationBuilder.AddColumn<DateOnly>(
                name: "shelf_life",
                schema: "grocerychef",
                table: "ingredients",
                type: "date",
                nullable: false,
                defaultValue: new DateOnly(1, 1, 1));
        }
    }
}
