//<auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GroceryChef.Api.Migrations.Applications
{
    /// <inheritdoc />
    public partial class Alter_RecipeIngredient : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_recipe_ingredients_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropForeignKey(
                name: "fk_recipe_ingredients_recipes_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropIndex(
                name: "ix_recipe_ingredients_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropIndex(
                name: "ix_recipe_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropColumn(
                name: "ingredients_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.AddPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients",
                columns: new[] { "ingredient_id", "recipe_id" });

            migrationBuilder.CreateIndex(
                name: "ix_recipe_ingredients_recipe_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "recipe_id");

            migrationBuilder.AddForeignKey(
                name: "fk_recipe_ingredients_ingredients_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "ingredient_id",
                principalSchema: "grocerychef",
                principalTable: "ingredients",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_recipe_ingredients_recipes_recipe_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "recipe_id",
                principalSchema: "grocerychef",
                principalTable: "recipes",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_recipe_ingredients_ingredients_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropForeignKey(
                name: "fk_recipe_ingredients_recipes_recipe_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropIndex(
                name: "ix_recipe_ingredients_recipe_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.AddColumn<string>(
                name: "ingredients_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "recipe_id");

            migrationBuilder.CreateIndex(
                name: "ix_recipe_ingredients_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "ingredient_id");

            migrationBuilder.CreateIndex(
                name: "ix_recipe_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "ingredients_id");

            migrationBuilder.AddForeignKey(
                name: "fk_recipe_ingredients_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "ingredients_id",
                principalSchema: "grocerychef",
                principalTable: "ingredients",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_recipe_ingredients_recipes_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "ingredient_id",
                principalSchema: "grocerychef",
                principalTable: "recipes",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
