//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GroceryChef.Api.Migrations.Applications
{
    /// <inheritdoc />
    public partial class Alter_Cart : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_cart_ingredient_cart_cart_id",
                schema: "grocerychef",
                table: "cart_ingredient");

            migrationBuilder.DropForeignKey(
                name: "fk_cart_ingredient_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "cart_ingredient");

            migrationBuilder.DropPrimaryKey(
                name: "pk_cart_ingredient",
                schema: "grocerychef",
                table: "cart_ingredient");

            migrationBuilder.DropPrimaryKey(
                name: "pk_cart",
                schema: "grocerychef",
                table: "cart");

            migrationBuilder.RenameTable(
                name: "cart_ingredient",
                schema: "grocerychef",
                newName: "cart_ingredients",
                newSchema: "grocerychef");

            migrationBuilder.RenameTable(
                name: "cart",
                schema: "grocerychef",
                newName: "carts",
                newSchema: "grocerychef");

            migrationBuilder.RenameIndex(
                name: "ix_cart_ingredient_ingredients_id",
                schema: "grocerychef",
                table: "cart_ingredients",
                newName: "ix_cart_ingredients_ingredients_id");

            migrationBuilder.AddColumn<DateTime>(
                name: "created_at_utc",
                schema: "grocerychef",
                table: "carts",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<DateTime>(
                name: "updated_at_utc",
                schema: "grocerychef",
                table: "carts",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "pk_cart_ingredients",
                schema: "grocerychef",
                table: "cart_ingredients",
                columns: new[] { "cart_id", "ingredients_id" });

            migrationBuilder.AddPrimaryKey(
                name: "pk_carts",
                schema: "grocerychef",
                table: "carts",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_cart_ingredients_carts_cart_id",
                schema: "grocerychef",
                table: "cart_ingredients",
                column: "cart_id",
                principalSchema: "grocerychef",
                principalTable: "carts",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_cart_ingredients_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "cart_ingredients",
                column: "ingredients_id",
                principalSchema: "grocerychef",
                principalTable: "ingredients",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_cart_ingredients_carts_cart_id",
                schema: "grocerychef",
                table: "cart_ingredients");

            migrationBuilder.DropForeignKey(
                name: "fk_cart_ingredients_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "cart_ingredients");

            migrationBuilder.DropPrimaryKey(
                name: "pk_carts",
                schema: "grocerychef",
                table: "carts");

            migrationBuilder.DropPrimaryKey(
                name: "pk_cart_ingredients",
                schema: "grocerychef",
                table: "cart_ingredients");

            migrationBuilder.DropColumn(
                name: "created_at_utc",
                schema: "grocerychef",
                table: "carts");

            migrationBuilder.DropColumn(
                name: "updated_at_utc",
                schema: "grocerychef",
                table: "carts");

            migrationBuilder.RenameTable(
                name: "carts",
                schema: "grocerychef",
                newName: "cart",
                newSchema: "grocerychef");

            migrationBuilder.RenameTable(
                name: "cart_ingredients",
                schema: "grocerychef",
                newName: "cart_ingredient",
                newSchema: "grocerychef");

            migrationBuilder.RenameIndex(
                name: "ix_cart_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "cart_ingredient",
                newName: "ix_cart_ingredient_ingredients_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_cart",
                schema: "grocerychef",
                table: "cart",
                column: "id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_cart_ingredient",
                schema: "grocerychef",
                table: "cart_ingredient",
                columns: new[] { "cart_id", "ingredients_id" });

            migrationBuilder.AddForeignKey(
                name: "fk_cart_ingredient_cart_cart_id",
                schema: "grocerychef",
                table: "cart_ingredient",
                column: "cart_id",
                principalSchema: "grocerychef",
                principalTable: "cart",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_cart_ingredient_ingredients_ingredients_id",
                schema: "grocerychef",
                table: "cart_ingredient",
                column: "ingredients_id",
                principalSchema: "grocerychef",
                principalTable: "ingredients",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
