//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GroceryChef.Api.Migrations.Applications
{
    /// <inheritdoc />
    public partial class Add_UserId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DELETE FROM grocerychef.recipes;
                DELETE FROM grocerychef.recipe_ingredients;
                DELETE FROM grocerychef.carts;
                DELETE FROM grocerychef.cart_ingredients;
                DELETE FROM grocerychef.ingredients;
                """);

            migrationBuilder.AddColumn<string>(
                name: "user_id",
                schema: "grocerychef",
                table: "recipes",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "user_id",
                schema: "grocerychef",
                table: "ingredients",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "user_id",
                schema: "grocerychef",
                table: "carts",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateIndex(
                name: "ix_recipes_user_id",
                schema: "grocerychef",
                table: "recipes",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_ingredients_user_id",
                schema: "grocerychef",
                table: "ingredients",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_carts_user_id",
                schema: "grocerychef",
                table: "carts",
                column: "user_id");

            migrationBuilder.AddForeignKey(
                name: "fk_carts_users_user_id",
                schema: "grocerychef",
                table: "carts",
                column: "user_id",
                principalSchema: "grocerychef",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_ingredients_users_user_id",
                schema: "grocerychef",
                table: "ingredients",
                column: "user_id",
                principalSchema: "grocerychef",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_recipes_users_user_id",
                schema: "grocerychef",
                table: "recipes",
                column: "user_id",
                principalSchema: "grocerychef",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_carts_users_user_id",
                schema: "grocerychef",
                table: "carts");

            migrationBuilder.DropForeignKey(
                name: "fk_ingredients_users_user_id",
                schema: "grocerychef",
                table: "ingredients");

            migrationBuilder.DropForeignKey(
                name: "fk_recipes_users_user_id",
                schema: "grocerychef",
                table: "recipes");

            migrationBuilder.DropIndex(
                name: "ix_recipes_user_id",
                schema: "grocerychef",
                table: "recipes");

            migrationBuilder.DropIndex(
                name: "ix_ingredients_user_id",
                schema: "grocerychef",
                table: "ingredients");

            migrationBuilder.DropIndex(
                name: "ix_carts_user_id",
                schema: "grocerychef",
                table: "carts");

            migrationBuilder.DropColumn(
                name: "user_id",
                schema: "grocerychef",
                table: "recipes");

            migrationBuilder.DropColumn(
                name: "user_id",
                schema: "grocerychef",
                table: "ingredients");

            migrationBuilder.DropColumn(
                name: "user_id",
                schema: "grocerychef",
                table: "carts");
        }
    }
}
