//<auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GroceryChef.Api.Migrations.Applications
{
    /// <inheritdoc />
    public partial class Alter_Recipe_And_Recreate_RecipeIngredient : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_recipe_ingredients_recipes_recipe_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropIndex(
                name: "ix_recipe_ingredients_recipe_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.AlterColumn<int>(
                name: "unit",
                schema: "grocerychef",
                table: "recipe_ingredients",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<decimal>(
                name: "amount",
                schema: "grocerychef",
                table: "recipe_ingredients",
                type: "numeric(4,1)",
                precision: 4,
                scale: 1,
                nullable: false,
                oldClrType: typeof(decimal),
                oldType: "numeric");

            migrationBuilder.AddPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients",
                columns: new[] { "recipe_id", "ingredient_id" });

            migrationBuilder.CreateIndex(
                name: "ix_recipe_ingredients_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "ingredient_id");

            migrationBuilder.AddForeignKey(
                name: "fk_recipe_ingredients_recipes_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "ingredient_id",
                principalSchema: "grocerychef",
                principalTable: "recipes",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_recipe_ingredients_recipes_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.DropIndex(
                name: "ix_recipe_ingredients_ingredient_id",
                schema: "grocerychef",
                table: "recipe_ingredients");

            migrationBuilder.AlterColumn<int>(
                name: "unit",
                schema: "grocerychef",
                table: "recipe_ingredients",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<decimal>(
                name: "amount",
                schema: "grocerychef",
                table: "recipe_ingredients",
                type: "numeric",
                nullable: false,
                oldClrType: typeof(decimal),
                oldType: "numeric(4,1)",
                oldPrecision: 4,
                oldScale: 1);

            migrationBuilder.AddPrimaryKey(
                name: "pk_recipe_ingredients",
                schema: "grocerychef",
                table: "recipe_ingredients",
                columns: new[] { "ingredient_id", "recipe_id" });

            migrationBuilder.CreateIndex(
                name: "ix_recipe_ingredients_recipe_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "recipe_id");

            migrationBuilder.AddForeignKey(
                name: "fk_recipe_ingredients_recipes_recipe_id",
                schema: "grocerychef",
                table: "recipe_ingredients",
                column: "recipe_id",
                principalSchema: "grocerychef",
                principalTable: "recipes",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
